config/routes.rb
LaunchSoon::Application.routes.draw do
  
  resources :reports

  resources :clientships

  resources :receipts
  
  resources :emails

  devise_for :users 
  
  root :to => 'emails#new'
 
  
end

app/models/clientship.rb
class Clientship < ActiveRecord::Base
  
  belongs_to :user
  belongs_to :client, :class_name => "User"
  
  attr_accessible :fee, :client_id
  
  validates_presence_of :user_id, :client_id
end

app/controllers/clientships_controller.rb
class ClientshipsController < ApplicationController
  
  filter_resource_access # declarative_authorization
  
  # GET /clientships
  # GET /clientships.json
  def index
    @clientships = current_user.clientships.all    

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @clientships }
    end
  end

  # GET /clientships/1
  # GET /clientships/1.json
  def show
    @clientship = current_user.clientships.find(params[:id])    

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @clientship }
    end
  end

  # GET /clientships/new
  # GET /clientships/new.json
  def new
    @clientship = Clientship.new
    @users = User.all


    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @clientship }
    end
  end

  # GET /clientships/1/edit
  def edit
    @clientship = Clientship.find(params[:id])
  end

  # POST /clientships
  # POST /clientships.json
  def create
    @clientship = current_user.clientships.build(:client_id => params[:client_id], :fee => params[:fee])

    respond_to do |format|
      if @clientship.save
        format.html { redirect_to @clientship, notice: 'Clientship was successfully created.' }
        format.json { render json: @clientship, status: :created, location: @clientship }
      else
        format.html { render action: "new" }
        format.json { render json: @clientship.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /clientships/1
  # PUT /clientships/1.json
  def update
    @clientship = current_user.clientships.find(params[:id])

    respond_to do |format|
      if @clientship.update_attributes(params[:clientship])
        format.html { redirect_to @clientship, notice: 'Clientship was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @clientship.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clientships/1
  # DELETE /clientships/1.json
  def destroy
    @clientship = current_user.clientships.find(params[:id])
    @clientship.destroy

    respond_to do |format|
      format.html { redirect_to clientships_url }
      format.json { head :ok }
    end
  end
end

app/helpers/clientships_helper.rb
module ClientshipsHelper
end

app/views/clientships/_add_clients_form.html.erb
<% @users.each do |user| %>
  	
	<%= form_tag clientships_path, :method => 'post' do %>
	  <p>
	    <%= user.email %> <br />
	    <%= hidden_field_tag :client_id, user.id %>
	    Monthly Fee: <%= text_field_tag :fee, params[:fee] %>
	    <%= submit_tag "Add as a client", :confirm => 'Are you sure this is your client?' %>
	  </p>
	<% end %>

<% end %>

app/views/clientships/_form.html.erb
<%= form_for(@clientship) do |f| %>
  <% if @clientship.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@clientship.errors.count, "error") %> prohibited this clientship from being saved:</h2>

      <ul>
      <% @clientship.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :fee %><br />
    <%= f.text_field :fee %>
  </div>
  
  <div class="actions">
    <%= f.submit %> | <%= link_to 'Cancel', clientships_path %>
  </div>
<% end %>

app/views/clientships/edit.html.erb
<% page_header "Edit client's fee"%>

<%= render 'form' %>

<%= link_to 'Cancel', clientships_path %>

app/views/clientships/index.html.erb
<%= stylesheet_link_tag  "styles/table" %>

<% page_header "Clients"%>

<br />
<div class="pagination">
<table id="hor-zebra">
  <tr>    
    <th>Client's fee</th>
    <th>Client's email</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @clientships.each do |clientship| %>
  <tr>    
    <td><%= clientship.fee %></td>
    <td><%= clientship.client.email %></td>
    <td><%= link_to 'Show', clientship %></td>
    <td><%= link_to 'Edit', edit_clientship_path(clientship) %></td>
    <td><%= link_to 'Destroy', clientship, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>
</div>
<br />

<%= link_to 'Add A New Client', new_clientship_path %>

app/views/clientships/new.html.erb
<% page_header "Add a new client"%>

<div class="column-large">
    <form role="search" method="get" id="searchform" action="http://workingwireframes.com/magframe/demo/" class="search" name="searchform">
        <input type="text" value="Search clients by their email..." onblur="if(this.value=='')this.value='Search stories...';" onfocus="if(this.value=='Search stories...')this.value=''" name="s" id="s" class="field"><input type="submit" value="Search" class="button-grey right">
    </form>
</div>


<%= render 'add_clients_form' %>

<%= link_to 'Back to Clients', clientships_path %>

app/views/clientships/show.html.erb
<p id="notice"><%= notice %></p>

<h3>The client's receipts</h3>

<p>
  <b>Client Email:</b>
  <%= @clientship.client.email %>
</p>

<p>
  <b>Client Fee:</b>
  <%= @clientship.fee %>
</p>


<%= link_to 'Edit', edit_clientship_path(@clientship) %> |
<%= link_to 'Back to clients', clientships_path %>

<p></p>
<% permitted_to? :read, :clientships do %>
				
	<div class="pagination">
		<table id="hor-zebra">
		  <tr>
		  	<th>Issued at</th>
		    <th>Type</th>
		    <th>Title</th>
		    <th>Amount</th>		    		    
		    <th></th>
		    <th></th>
		    <th></th>
		  </tr>
		
		<% @clientship.client.receipts.each do |receipt| %>
		  <tr class="odd">
		  	<td><%= receipt.issued_at %></td>
		    <td><%= receipt.payment %></td>
		    <td><%= receipt.title %></td>
		    <td><%= receipt.amount %></td>		    		    
		    <td><%= link_to 'Show', receipt %></td>
		    <td><%= link_to 'Edit', edit_receipt_path(receipt) %></td>
		    <td><%= link_to 'Destroy', receipt, confirm: 'Are you sure?', method: :delete %></td>
		  </tr>
		<% end %>
		</table>
		</div>	
	
	<br />	
	
	<%= link_to 'Find More Clients', new_clientship_path %>

<% end %>