config/routes.rb
LaunchSoon::Application.routes.draw do
  
  resources :reports

  resources :clientships

  resources :receipts
  
  resources :emails

  devise_for :users 
  
  root :to => 'emails#new'
 
  
end

app/models/receipt.rb
class Receipt < ActiveRecord::Base
  
  belongs_to :user 
  attr_accessible :payment, :title, :amount, :description, :issued_at, 
  :photo, :photo_file_name, :photo_content_type, :photo_file_size, :photo_updated_at
  
  validates_presence_of :user_id, :payment, :issued_at, :payment
  
  has_attached_file :photo, :styles => { :small => "150x150>" },   
    #:url => "/assets/receipts/:id/:style/:basename.:extension",
    #:path => ":rails_root/app/assets/receipts/:id/:style/:basename.:extension"
    #:default_url => "/images/photo01.jpg"    
    :storage => :s3,
    :s3_credentials => "#{Rails.root}/config/s3.yml",    
    :bucket => 'myshoebox' # "paperclip-example-bucket-#{Rails.env}"           
    
  #validates_attachment_presence :photo
  validates_attachment_size :photo, :less_than => 5.megabytes
  validates_attachment_content_type :photo, :content_type => ['image/tiff', 'image/jpeg', 'image/jpg', 
    'image/png', 'image/gif', 'application/pdf', 'application/doc', 'application/docx']
               
  def self.search(start_at, end_at)
    if start_at && end_at
      where('issued_at >= ? && issued_at <= ?', start_at, end_at)
    else
      scoped
    end
  end    
   
end

app/controllers/receipts_controller.rb
class ReceiptsController < ApplicationController
  
  filter_resource_access # declarative_authorization
  
  # GET /receipts
  # GET /receipts.json
  def index
    @receipts = current_user.receipts.all
    @receipts_list = Receipt.where("user_id" => current_user.id).paginate(:per_page => 2, :page => params[:page])    
    @date = params[:month] ? Date.parse(params[:month]) : Date.today
    @view_format = params[:view] || 'list'    
  end

  # GET /receipts/1
  # GET /receipts/1.json
  def show
    @receipt = Receipt.find(params[:id]) 

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @receipt }
    end
  end

  # GET /receipts/new
  # GET /receipts/new.json
  def new
    @receipt = Receipt.new    

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @receipt }
    end
  end

  # GET /receipts/1/edit
  def edit
    @receipt = Receipt.find(params[:id])
  end

  # POST /receipts
  # POST /receipts.json
  def create
    @receipt = current_user.receipts.build(params[:receipt])

    respond_to do |format|
      if @receipt.save!
        format.html { redirect_to @receipt, notice: 'Receipt was successfully created.' }
        format.json { render json: @receipt, status: :created, location: @receipt }
      else
        format.html { render action: "new" }
        format.json { render json: @receipt.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /receipts/1
  # PUT /receipts/1.json
  def update
    @receipt = Receipt.find(params[:id])

    respond_to do |format|
      if @receipt.update_attributes(params[:receipt])
        format.html { redirect_to @receipt, notice: 'Receipt was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @receipt.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /receipts/1
  # DELETE /receipts/1.json
  def destroy
    @receipt = Receipt.find(params[:id])
    @receipt.destroy

    respond_to do |format|
      format.html { redirect_to receipts_url }
      format.json { head :ok }
    end
  end
end

app/helpers/receipts_helper.rb
module ReceiptsHelper
  
  def view_style_selector
    if @view_format=='calendar' 
      @list_style_display = 'display: none'
      @calendar_style_display = 'display: block'
      true
    else
      @calendar_style_display = 'display: none'
      @list_style_display = 'display: block'
      false
    end           
    
  end
    
  
end

app/views/receipts/_form.html.erb
<%= form_for @receipt, :html => { :multipart => true } do |f| %>
  <% if @receipt.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@receipt.errors.count, "error") %> prohibited this receipt from being saved:</h2>

      <ul>
      <% @receipt.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :payment %><br />
    <% @payment_type = [["Expense", "Expense"] , ["Income", "Income"]] %>
    <%= f.select :payment, @payment_type %>
  </div>
  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :amount %><br />
    <%= f.text_field :amount %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :issued_at %><br />
    <%= f.text_field :issued_at, :value => @receipt.issued_at || h(Date.today) %>
  </div>
  
  <div class="field">
    <%= f.label :photo, "Photo" %>
    <%= f.file_field :photo %>
  </div>
  
  <div class="actions">
    <%= f.submit %> | <%= link_to 'Cancel', receipts_path %>
  </div>
<% end %>

app/views/receipts/edit.html.erb
<% page_header "Edit receipt"%>

<%= render 'form' %>

app/views/receipts/index.html.erb
<% page_header "Receipts"%>

<%= radio_button_tag :view, 'list', !view_style_selector %> View list  <%= radio_button_tag :view, 'calendar', view_style_selector %> View calendar

<div id="list" style="<%= @list_style_display %>">
	<div class="pagination">
	<table id="hor-zebra">
	  <tr>
	  	<th>Issued at</th>
	    <th>Type</th>
	    <th>Title</th>
	    <th>Amount</th>       
	    <th></th>
	    <th></th>
	    <th></th>
	  </tr>
	
	<% @receipts_list.each do |receipt| %>
	  <tr>
	  	<td><%= receipt.issued_at %></td>
	    <td><%= receipt.payment %></td>
	    <td><%= receipt.title %></td>
	    <td><%= receipt.amount %></td>        
	    <td><%= link_to 'Show', receipt %></td>
	    <td><%= link_to 'Edit', edit_receipt_path(receipt) %></td>
	    <td><%= link_to 'Destroy', receipt, confirm: 'Are you sure?', method: :delete %></td>
	  </tr>
	<% end %>
	</table>
	</div>
	
	<%= will_paginate @receipts_list %>

</div>

<br />

<div id="calendar" style="<%= @calendar_style_display %>" >
  <h2 id="month">
    <%= link_to "&lang;".html_safe, :month => (@date.beginning_of_month-1).strftime("%B %Y"), :view => 'calendar' %>
    <%=h @date.strftime("%B %Y") %>
    <%= link_to "&rang;".html_safe, :month => (@date.end_of_month+1).strftime("%B %Y"), :view => 'calendar' %>
  </h2>
  <%= calendar_for @receipts, :year => @date.year, :month => @date.month do |calendar| %>
    <%= calendar.head('Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday') %>
    <%= calendar.day(:day_method => :issued_at) do |date, receipts| %>
      <%= date.day %>
      <ul>
        <% for receipt in receipts %>
          <li><%= link_to h(receipt.title), receipt %></li>
        <% end %>
      </ul>
    <% end %>
  <% end %>
</div>	

<%= link_to 'Add A New Receipt', new_receipt_path %>

<br />	

app/views/receipts/new.html.erb
<% page_header "Add a new receipt"%>

<%= render 'form' %>

app/views/receipts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Payment Type:</b>
  <%= @receipt.payment %>
</p>

<p>
  <b>Title:</b>
  <%= @receipt.title %>
</p>

<p>
  <b>Amount:</b>
  <%= @receipt.amount %>
</p>

<%= link_to image_tag( @receipt.photo.url(:small) ), @receipt.photo.url(:original) %>

<p>
  <b>Description:</b>
  <%= @receipt.description %>
</p>

<p>
  <b>Issued at:</b>
  <%= @receipt.issued_at %>
</p>


<%= link_to 'Edit', edit_receipt_path(@receipt) %> |
<%= link_to 'Back to receipts', receipts_path %>