config/routes.rb
LaunchSoon::Application.routes.draw do
  
  resources :reports

  resources :clientships

  resources :receipts
  
  resources :emails

  devise_for :users 
  
  root :to => 'emails#new'
 
  
end

app/models/report.rb
class Report < ActiveRecord::Base
  validates_presence_of :start_at, :end_at, :user_id   
  belongs_to :user
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  
  filter_resource_access # declarative_authorization
  # GET /reports
  # GET /reports.json
  def index
    @reports = current_user.reports.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @reports }
    end
  end

  # GET /reports/1
  # GET /reports/1.json
  def show
    @report = current_user.reports.find(params[:id])
    @receipts = current_user.receipts.search(@report.start_at, @report.end_at).paginate(:per_page => 2, :page => params[:page])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @report }
    end
  end

  # GET /reports/new
  # GET /reports/new.json
  def new
    @report = Report.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @report }
    end
  end

  # GET /reports/1/edit
  def edit
    @report = current_user.reports.find(params[:id])
  end

  # POST /reports
  # POST /reports.json
  def create
    @report = current_user.reports.build(params[:report])

    respond_to do |format|
      if @report.save
        format.html { redirect_to @report, notice: 'Report was successfully created.' }
        format.json { render json: @report, status: :created, location: @report }
      else
        format.html { render action: "new" }
        format.json { render json: @report.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /reports/1
  # PUT /reports/1.json
  def update
    @report = current_user.reports.find(params[:id])

    respond_to do |format|
      if @report.update_attributes(params[:report])
        format.html { redirect_to @report, notice: 'Report was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @report.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reports/1
  # DELETE /reports/1.json
  def destroy
    @report = current_user.reports.find(params[:id])
    @report.destroy

    respond_to do |format|
      format.html { redirect_to reports_url }
      format.json { head :ok }
    end
  end
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/views/reports/_form.html.erb
<%= form_for(@report) do |f| %>
  <% if @report.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@report.errors.count, "error") %> prohibited this report from being saved:</h2>

      <ul>
      <% @report.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :start_at %><br />
    <%= f.date_select :start_at %>
  </div>
  <div class="field">
    <%= f.label :end_at %><br />
    <%= f.date_select :end_at %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/reports/edit.html.erb
<% page_header "Edit report"%>

<%= render 'form' %>

<%= link_to 'Show', @report %> |
<%= link_to 'Back', reports_path %>

app/views/reports/index.html.erb
<% page_header "Reports"%>

<div class="pagination">
<table id="hor-zebra">
  <tr>
    <th>Title</th>
    <th>Start at</th>
    <th>End at</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @reports.each do |report| %>
  <tr>
    <td><%= report.title %></td>
    <td><%= report.start_at %></td>
    <td><%= report.end_at %></td>
    <td><%= link_to 'Show', report %></td>
    <td><%= link_to 'Edit', edit_report_path(report) %></td>
    <td><%= link_to 'Destroy', report, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>
</div>
<br />

<%= link_to 'New Report', new_report_path %>

app/views/reports/new.html.erb
<% page_header "Create a new report"%>

<%= render 'form' %>

<%= link_to 'Back', reports_path %>

app/views/reports/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @report.title %>
</p>

<p>
  <b>Start at:</b>
  <%= @report.start_at %>
</p>

<p>
  <b>End at:</b>
  <%= @report.end_at %>
</p>

<h3>Report of Receipts</h3>

<div id="list">
	<div class="pagination">
	<table id="hor-zebra">
	  <tr>
	  	<th>Issued at</th>
	    <th>Type</th>
	    <th>Title</th>
	    <th>Amount</th>       
	    <th></th>	    
	  </tr>
	
	<% @receipts.each do |receipt| %>
	  <tr>
	  	<td><%= receipt.issued_at %></td>
	    <td><%= receipt.payment %></td>
	    <td><%= receipt.title %></td>
	    <td><%= receipt.amount %></td>        
	    <td><%= link_to 'Show', receipt %></td>	    
	  </tr>
	<% end %>
	</table>
	</div>
	
	<%= will_paginate @receipts %>

</div>

<br />



<%= link_to 'Edit', edit_report_path(@report) %> |
<%= link_to 'Back', reports_path %>