config/routes.rb
LaunchSoon::Application.routes.draw do
  
  resources :reports

  resources :clientships

  resources :receipts
  
  resources :emails

  devise_for :users 
  
  root :to => 'emails#new'
 
  
end

app/views/layouts/_application_footer.html.erb
<div id="footer">
            <div class="container">
                <div class="right">
                    <ul class="social">
                        <li class="rss">
                            <a href="#"></a>
                        </li><!--
            <li class="twitter"><a href="http://twitter.com"></a></li>
            <li class="facebook"><a href="http://facebook.com"></a></li>
            <li class="flickr"><a href="http://flickr.com"></a></li>
            <li class="dribbble"><a href="http://dribbble.com"></a></li>
            -->
                    </ul>
                </div>
                <div class="left">
                    <ul>
                        <li class="header">
                            <p>
                                <strong>REALTORLY</strong>
                            </p>
                        </li>	
                        <li><a href="#" title="View all posts filed under Blogs">Blogs</a></li>
                        <li><a href="#" title="View all posts filed under Business">Business</a></li>	
                    </ul>
                    <!-- Removing or editing the paragraph below is violating your license. -->
                    <p class="meta">
                        © Copyright 2011 <a href="http://workingwireframes.com/magframe/demo/">Magframe</a>. 
                    </p>
                </div>
                <div class="clear"></div>
            </div>
        </div>	

app/views/layouts/_application_top_menu.html.erb
<div class="navigation">
                <div class="container">
                    <ul class="categories">                    	
                    	<% if user_signed_in? %>
							<li><%= link_to "Receipts", receipts_url %>
								<ul class="children">
									<li><%= link_to "Add New Receipt", new_receipt_url %></li>							
								</ul>
							</li>
							
							<li><%= link_to "Reports", reports_url %>
								<ul class="children">
									<li><%= link_to "Create New Report", new_report_url %></li>							
								</ul>
							</li>
							<% permitted_to? :read, :clientships do %>
							<li><%= link_to "Clients", clientships_url %>
								<ul class="children">
									<li><%= link_to "Find More Clients", new_clientship_url %></li>							
								</ul>
							</li>							
							<% end %>
							
						<% else %>
							
						<% end %>                     	                    	                    						
						
					</ul>
				
                    <ul class="pages">                    	
                    	<% if user_signed_in? %>                    		                    	                   	                   
                        	<li><%= link_to "Sign out", destroy_user_session_path, :method => :delete %>                        	
                        	</li>                        							
						<% else %>
							<li><%= link_to "Sign in", new_user_session_url %></li>
						<% end %>                        
                        											
                    </ul>
                    <div class="clear"></div>
                </div>
            </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>My Shoe Box</title>
  <%= stylesheet_link_tag  "styles" %>
  <%= javascript_include_tag "application" %>  
  <%= csrf_meta_tags %>
  <%= yield(:head) %>
</head>
<body>	
	   <div id="header">
            <div class="container">
                <div class="branding">
                    <h1 class="logo">
                    	<%= image_tag "shoe-box-hi.png", :size => "42x40" %>	
                        <%= link_to 'My Shoebox', root_url %><br />
                        <p class="slogan">Your Accountant Wants You Organized!</p>                        
                    </h1>
                </div>
                
                <div class="clear"></div>
            </div>
            <%= render "layouts/application_top_menu" %>
        </div>        
        <div id="main">
            <div class="container">
            	<p id="email"><%= current_user.email if current_user %></p>
            	
            	<div class="title">
                    <h3><%= yield(:h3) %></h3>                                   
                </div>
            	                                                                                   
                <div class="content">
                    <div class="page">
                        <div class="entry">
                            <div class="thumbnail"></div>
                            
							<p class="alert"><%= alert %></p>
							<%= yield %>	                        
                        <div class="clear"></div>
                        </div>                    
                    </div>                
				</div>        

				<div class="sidebar">
            		<div class="ad">
            			<%= image_tag "organizer.jpg", :size => "363x350" %>                		
                		
                	</div>
                </div>                
                
                <div class="clear"></div>
       		</div>                             
   		</div>        
        <%= render "layouts/application_footer"%>		

</body>
</html>

app/views/layouts/receipts.html.erb
<% stylesheet  "styles/table" %> 
<% stylesheet  "styles/calendar" %>
<% stylesheet  "http://ajax.googleapis.com/ajax/libs/jqueryui/1.7.2/themes/redmond/jquery-ui.css" %>
<% javascript "http://ajax.googleapis.com/ajax/libs/jquery/1.4.2/jquery.min.js", "http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.1/jquery-ui.min.js" %>

<%= render :file => 'layouts/application' %>